version: '3.1'
services:
  app:
    container_name: express_server
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  mongo:
    container_name: mongo
    image: mongo:3.2.6
    restart: always
  mongo-seed:
    image: mongo:3.2.6
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      'bash -c "mongoimport --host mongo --port 27017 --db test --collection countries --drop --file /mongo-seed/countries.json & mongoimport --host mongo --port 27017 --db test --collection cities --drop --file /mongo-seed/cities.json "'